name: Conventional Pull Request
# See https://github.com/Namchee/conventional-pr

on:
  pull_request:
    types: [opened, reopened, ready_for_review] # Currently, this action only support these events

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
